### ISSUE TITLE
Style Child Theme

### ISSUE THREAD

**Issue by deblala** [lalaprojects-dev/llt5-bay-view#2]
STAGING SITE
https://bayview.cloudaccess.host/ 

INVISION APP
https://invis.io/UW13FWUCFNPB#/476056679_Home_Page_Duo

SKETCH DOC
Is in the Sketch App Online (Password in Keeper)
https://www.sketch.com/s/dda8e0db-5894-407a-8c87-6fe0a397ff64

OVERVIEW
There are some fancy logo and style issues to deal with in this design concept.  
They have 3 different logos and 2 different styles
I would like to walk you through the design concept to get your recommendations on the best approach.  Please schedule a time for us to meet, I am trying out this new gmail booking page, give is a whirl, let's see how it works. https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ28sFVYC72o9-2bJ7CAt3yemDQ-3bs_dqzgnmL60k6F5zrTdsh_Eqvw1wmvurIv8SOdp7IRHD1d 

STYLE
In the task, I think is it safe for you to style the basics and global elements.  We will deal with the unusual elements in other issues
- [x] Add a Child Theme
- [x] The Basics
- [x] Header, Nav, Bay View at Gallagher Farms Logo # 1,
- [x] Top Nav Bar
- [x] Footer

FONTS
I am going to need to buy you these specialty web fonts. https://creativemarket.com/sansandsons/3712038-Le-French-Organic-Paired-Duo  I'll do this tomorrow with the client.

DEV ASSETS
I have a folder started here
https://drive.google.com/drive/u/0/folders/1yYI6QAZTFeL4e4lAzRQVVIAzWkb-myso

**Comment by bdb5075** [comment]
Hi @deblala I think I have everything styled that you wanted so far but let me know!

https://bayview.cloudaccess.host/

Really love the design!

**Comment by deblala** [comment]
Ah thanks @bdb5075 the basics are looking good so far!
